### ISSUE TITLE
Link all the previous implemented functionalities

### ISSUE THREAD

**Issue by nicoscudo** [nicoscudo/openairquality#7]

**Comment by nicoscudo** [comment]
Merged previous implementations on commit 1be793bde144db7d9fcd430dc4364921ea2fd893

**Comment by Gap-98** [comment]
implemented login in main on commit 5e3d7cf3c258f516b384ffafa55777c46f5a0e04

**Comment by SaraBettanin** [comment]
Implementation completed also for argparse+fixed bugs on commit 012edf539477b69e413c2863917a56dc52c3afd2
